# Site Info
title:              "Gradient Ascent"
description:        "A blog and shared knowledge repository"
author_name:        "Sahil Hasan and Andrew Cui"
logo_url:           https://avatars1.githubusercontent.com/u/4761944?v=4 #TODO: change this to a proper logo

# Site Settings
plugins:
  - jekyll-remote-theme

remote_theme: heiswayi/the-plain
permalink:          /:title # Post permalink
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Building
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed


# Other things
plugins:
  - jekyll-sitemap
