# Site Info
title:              "Gradient Ascent"
description:        "A blog and shared knowledge repository"
author_name:        "Sahil Hasan and Andrew Cui"
logo_url:           https://raw.githubusercontent.com/sahilhasan/gradientascent/master/assets/tmp_logo.png

# Site Settings
plugins:
  - jekyll-remote-theme

remote_theme: heiswayi/the-plain
permalink:          /:title # Post permalink
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Building
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed


# Other things
plugins:
  - jekyll-sitemap
